### ISSUE TITLE
what are our steps for getting to a releasable v0.1.0 geo standard?

### ISSUE THREAD

**Issue by lukereeve** [urban-stack/OpenZoning#13]
steps
- ...

sub-question
- ...

**Comment by paulsalama** [comment]
@lukereeve Are you imagining these "steps" are different than what's needed to get to a releasable v0.1 _data_ standard? (per #12)

**Comment by lukereeve** [comment]
@paulsalama good question: I think no, in general. I'm posing this question aimed at the specifics, thinks I don't know anything about, such as developing a geospatial schema, storing geospatial/polygon data in a geojson, and using Kart.
