### ISSUE TITLE
Ensure OZFS data structure adheres to valid JSON

### ISSUE THREAD

**Issue by lukereeve** [urban-stack/OpenZoning#2]
@paulsalama's question from the [6/8] team meeting. 
aiding questions
-  Where do we start in answering this question?

**Comment by paulsalama** [comment]
Look at [JSON](https://www.json.org/json-en.html) standard for reference.

**Comment by paulsalama** [comment]
Structure of nested objects `{ : }` and arrays `[ ]`, with data values separated by commas `,`
As per [JSON](https://www.json.org/json-en.html) reference

Automated JSON validator in Github is here: https://github.com/marketplace/actions/validate-json
(Though this seems to require a _schema_, which we obviously don't have yet!)

**Comment by lukereeve** [comment]
@paulsalama I've created a Python script to parse our json file and can confirm that it is valid! I'll close this thread and start a new one about creating a schema and using the automated JSON validator for it
