### ISSUE TITLE
points vs. polygons vs. polylines: which ones?

### ISSUE THREAD

**Issue by lukereeve** [urban-stack/OpenZoning#3]
per @c-voulgaris and @paulsalama discussion on the 6/8 agenda, how should we structure the geospatial data?

**Comment by paulsalama** [comment]
We discussed the question of whether district/overlay/etc. geospatial data could be saved to each individual parcel, and then the parcels stored as points (i.e. centroids). Reasons to do this include:
- Some municipalities geospatially store districts by parcel, while others by polygon/zone (though it's assumed that the official maps are "polygons")
- Efficient data storage and analysis

Based on the principle of storing data as close to the original source as possible (alt. not overly interpreting), we decided that **geospatial data should be stored as polygons**. Exactly how, TBD.

Similarly, data storage around parcels is TBD. Based on my experience at Envelope, parcels may eventually need to be _exploded_ into polylines.
