### ISSUE TITLE
task: geospatially resolving Minneapolis

### ISSUE THREAD

**Issue by lukereeve** [urban-stack/OpenZoning#7]
with Minneapolis's unique geospatial layer structure - built form overlay districts assigned at the parcel level and primary districts assigned at the city scale - how do we assign key value pairs? 

@paulsalama , I don't think i'm transcribing this issues quite right, would appreciate you filling in my knowledge gaps

**Comment by paulsalama** [comment]
Screenshots from GIS should go here. May help decide/define issue #9.

**Comment by lukereeve** [comment]
geojson specifications: https://datatracker.ietf.org/doc/html/rfc7946#section-3.2
