### ISSUE TITLE
How should we record variations in constraint values, in both the UI/UX and the data standard?

### ISSUE THREAD

**Issue by lukereeve** [urban-stack/OpenZoning#8]
How can we consistently (i.e. in a modular way) record the different types of code-stipulated constraint variations?

- [ ] Be more specific about what _variation_ means here (@lukereeve)
- [x] Look up what Paul wrote about "variations" last month (June)
- [x] Enumerate the different types of variations (see https://github.com/urban-stack/OpenZoning/issues/8#issuecomment-1181965697)

**Comment by paulsalama** [comment]
There are a few different types of "variations", as per https://github.com/urban-stack/OpenZoning/tree/main/data-standard#open-questions
