### ISSUE TITLE
Looking up and storing district data - Maintaining Layers vs. Atomization

### ISSUE THREAD

**Issue by paulsalama** [urban-stack/OpenZoning#9]
This is complex, and there may not be a single answer yet. 
The question is whether all geospatial layers (base zoning, overlays, special districts, etc.) should be stacked and intersected to create a single layer where each polygon is differentiated (atomized) from its neighbors in one or more of the districts & lookups. OR should the intersection only be done with parcel data?

Similarly, on the data side, should the JSON correspond to each individual combination of (atomized) districts, or can a parcel lookup search through multiple (higher-level) districts?

It's unclear at the moment to what degree the answer to the geospatial question determines the data question & vice versa.

This issue needs some visuals...
Inspired by/Related to #7

**Comment by lukereeve** [comment]
6/28 huddle
notes
- CV: e.g., surrounding building stipulations being categorized as "buffer" districts
- want to do as little resolving/interpreting as possible
- ?: would the data structure for the X different types 
- proposed structure: 1 json schema for a base district and another one for overlay, buffer, etc. districts, denoting starting point districts from supplementary/augmenting districts
-

**Comment by paulsalama** [comment]
@lukereeve my thought was we could lean on [Kart](https://kartproject.org/) for geospatial layer maintenance.

**Comment by paulsalama** [comment]
## The Problems
### Geospatial Atomization problem
Intersecting the various districts and subdistricts to create unique combo district lookups (i.e. `R2B` base zoning district + `Interior 3` overlay -> `R2B-BFI3`) is an _exponential_ operation, quickly leading to overwhelming numbers of (atomized) "districts".

For example, in Minneapolis, the combination of **26 base zoning districts** and **14 built form overlays** means that over 200 _combo_ districts exist in the city. See image:
![image](https://user-images.githubusercontent.com/18361305/177868809-c260440c-988c-4ebf-9496-f3c8032c192c.png)

### Data (standard) problem
From the data entry vantage point, the combined districts also need to be _individually_ or uniquely coded. Extremely laborious, yes, but basically impossible to maintain.
This would mean a full rules definition entry in the JSON for each combo: `R2B-BFI3`, `R2-BFC2`, `OR2-BFT1`, etc.

## Our response
Rather than doing the work to combine the data/rules and intersect the geospatial layers, we maintain the layers (mostly) as-is and only code the relevant/applicable portion of zoning rules & constraints. This would depend on defining a clear hierarchy of layers, and ability to test/validate that through the "stack" of layers, all constraints are covered (per #1). For Minneapolis (in response to #7), we maintain layers of: City, Base Zoning, Built Form Overlay District, Overlay, and (eventually) Buffer Rules

![image](https://user-images.githubusercontent.com/18361305/177871749-ed8b3f1b-d6dd-4826-b36f-3b49591cdd1b.png)

#### Overlays
There are 14 "Overlay" districts, which I have not yet run analyses on to understand the number of intersections/combinations:
![image](https://user-images.githubusercontent.com/18361305/177870090-743a0af4-822f-4601-bfa3-05f141955d01.png)

**Comment by lukereeve** [comment]
For v0.1.0, we've decided on maintaining layers.

**Comment by paulsalama** [comment]
@paulsalama to document here: https://github.com/urban-stack/OpenZoning/tree/main/geo-standard
